name: temporal-server
version: '1.29.7'
summary: Temporal server
description: |
  Temporal server as a snap.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots
base: core24

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  temporal-server:
    daemon: simple
    command: bin/run-temporal
    plugs: [home, network, network-bind]

  init-postgres:
    command: bin/init-postgres
    plugs: [home, network]


  init-sqlite:
    command: bin/init-sqlite
    plugs: [home, network]

parts:
  temporal:
    plugin: nil
    source: https://github.com/temporalio/temporal/releases/download/v1.29.7/temporal_1.29.7_linux_amd64.tar.gz 
    source-checksum: sha256/e0177f9903facbf631466d7f86c3323bfec3fdf6dc704e749ca7e754d13fb622
    override-pull: |
      set -eux
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/bin
      mv temporal-server $CRAFT_PART_INSTALL/bin
      mv temporal-sql-tool $CRAFT_PART_INSTALL/bin 
      mkdir -p $CRAFT_PART_INSTALL/usr/share/temporal-server/
      mv config $CRAFT_PART_INSTALL/usr/share/temporal-server/
    stage:
      - bin/temporal-server
      - bin/temporal-sql-tool
      - usr/share/temporal-server/config
    prime:
      - bin/temporal-server
      - bin/temporal-sql-tool
      - usr/share/temporal-server/config
  temporal-schema:
    plugin: nil
    source: https://github.com/temporalio/temporal/archive/refs/tags/v1.29.7.tar.gz
    override-pull: |
      set -eux
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/share/temporal-server/
      mv schema $CRAFT_PART_INSTALL/usr/share/temporal-server/
    stage:
      - usr/share/temporal-server/schema
    prime:
      - usr/share/temporal-server/schema
  tree:
    plugin: dump
    source: snap/local/tree
