name: temporal-server
version: '1.27.1'
summary: Temporal server
description: |
  Temporal server as a snap.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots
base: core24

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  temporal-server:
    daemon: simple
    command: bin/run-temporal
    plugs: [home, network, network-bind]

  init-postgres:
    command: bin/init-postgres
    plugs: [home, network]

parts:
  temporal:
    plugin: nil
    source: https://github.com/temporalio/temporal/releases/download/v1.27.1/temporal_1.27.1_linux_amd64.tar.gz
    source-checksum: sha256/8df9570b806e6eb447ad06498581fbe5b2b3cb624b18768f32c18a14f38e6832
    override-pull: |
      set -eux
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/bin
      mv temporal-server $CRAFT_PART_INSTALL/bin
      mv temporal-sql-tool $CRAFT_PART_INSTALL/bin 
      mkdir $CRAFT_PART_INSTALL/usr/share/temporal-server/
      mv config $CRAFT_PART_INSTALL/usr/share/temporal-server/
    stage:
      - bin/temporal-server
      - bin/temporal-sql-tool
      - usr/share/temporal-server/config
    prime:
      - bin/temporal-server
      - bin/temporal-sql-tool
      - usr/share/temporal-server/config
  temporal-schema:
    plugin: nil
    source: https://github.com/temporalio/temporal/archive/refs/tags/v1.27.1.tar.gz
    override-pull: |
      set -eux
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/share/temporal-server/
      mv schema $CRAFT_PART_INSTALL/usr/share/temporal-server/
    stage:
      - usr/share/temporal-server/schema
    prime:
      - usr/share/temporal-server/schema
  tree:
    plugin: dump
    source: snap/local/tree
